version: "3.8"

services:
  localstack:
    container_name: aws-localstack
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3:4566
      - HOSTNAME_EXTERNAL=localhost
      - DEBUG=1
      - PORT_WEB_UI=4510
      - AWS_DEFAULT_REGION=ap-south-1
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_ACCESS_KEY_ID=admin
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
